version: "3.7"
services:
  app:
    build:
      args:
        user: user
        uid: 1000
      context: ./
      dockerfile: Dockerfile
    image: ghorsheba
    container_name: ghorsheba-app
    working_dir: /var/www/
    volumes:
      - ./:/var/www
    networks:
      - ghorsheba

  db:
    image: mysql:8.0
    container_name: ghorsheba-db
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      # MYSQL_USER: ${DB_USERNAME}
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    # ports:
    #     - 33061:3306
    volumes:
      - ./docker-compose/mysql:/docker-entrypoint-initdb.d
    networks:
      - ghorsheba

  nginx:
    image: nginx:alpine
    container_name: ghorsheba-nginx
    ports:
      - 8081:80
    volumes:
      - ./:/var/www
      - ./docker-compose/nginx:/etc/nginx/conf.d/
    networks:
      - ghorsheba

  # Database management
  pma:
    image: phpmyadmin:5.1
    container_name: ghorsheba-pma
    environment:
       - PMA_ARBITRARY=1
       - PMA_HOST=${DB_HOST}
       - PMA_USER=${DB_USERNAME}
       - PMA_PASSWORD=${DB_PASSWORD}
       - PMA_PORT=${DB_PORT}
    depends_on:
       - db
    ports:
       - 8082:80
    networks:
      - ghorsheba

networks:
  ghorsheba:
    driver: bridge

volumes:
    dbdata:
